#!/bin/bash

ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-es-logging.default.svc}
ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT:-9200}
ELASTICSEARCH_SCHEME=${ELASTICSEARCH_SCHEME:-http}

ELASTICSEARCH_REQUEST_TIMEOUT=${ELASTICSEARCH_REQUEST_TIMEOUT:-5s}

FLUENTD_LOGSTASH_FORMAT=${FLUENTD_LOGSTASH_FORMAT:-true}
FLUENTD_LOGSTASH_PREFIX=${FLUENTD_LOGSTASH_PREFIX:-logstash}
FLUENTD_LOGSTASH_DATEFORMAT=${FLUENTD_LOGSTASH_DATEFORMAT-'%Y.%m.'}

FLUENTD_ENABLE_BUFFERING=${FLUENTD_ENABLE_BUFFERING:-true}
FLUENTD_FLUSH_INTERVAL=${FLUENTD_FLUSH_INTERVAL:-10s}
FLUENTD_FLUSH_THREADS=${FLUENTD_FLUSH_THREADS:-4}
FLUENTD_RETRY_LIMIT=${FLUENTD_RETRY_LIMIT:-10}
FLUENTD_DISABLE_RETRY_LIMIT=${FLUENTD_DISABLE_RETRY_LIMIT:-true}
FLUENTD_RETRY_WAIT=${FLUENTD_RETRY_WAIT:-1s}
FLUENTD_MAX_RETRY_WAIT=${FLUENTD_MAX_RETRY_WAIT:-60s}
FLUENTD_BUFFER_QUEUE_FULL_ACTION=${FLUENTD_BUFFER_QUEUE_FULL_ACTION:-exception}
FLUENTD_BUFFER_CHUNK_LIMIT=${FLUENTD_BUFFER_CHUNK_LIMIT:-8m}
FLUENTD_BUFFER_QUEUE_LIMIT=${FLUENTD_BUFFER_QUEUE_LIMIT:-8192}
FLUENTD_BUFFER_TYPE=${FLUENTD_BUFFER_TYPE:-memory}
FLUENTD_BUFFER_PATH=${FLUENTD_BUFFER_PATH:-/var/fluentd/buffer}

KUBERNETES_PRESERVE_JSON_LOG=${KUBERNETES_PRESERVE_JSON_LOG:-true}
KUBERNETES_FETCH_METADATA=${KUBERNETES_FETCH_METADATA:-true}
KUBERNETES_URL=${KUBERNETES_URL:-https://kubernetes.default.svc}
KUBERNETES_VERIFY_SSL=${KUBERNETES_VERIFY_SSL:-true}

mkdir -p /etc/fluent

# Only set a config if one doesn't already exist. This is to allow
# a user to provide their own by mounting a configMap, etc.
if ! [ -f /etc/fluent/fluent.conf ];then

cat << EOF >> /etc/fluent/fluent.conf
# Prevent fluentd from handling records containing its own logs. Otherwise
# it can lead to an infinite loop, when error in sending one message generates
# another message which also fails to be sent and so on.
<match fluent.**>
  @type null
</match>

# input plugin that exports metrics
<source>
  @type prometheus
</source>

# input plugin that collects metrics from MonitorAgent
<source>
  @type prometheus_monitor
</source>

# Logs from systemd-journal for interesting services.
<source>
  @type systemd
  filters [{ "_SYSTEMD_UNIT": "docker.service" }]
  pos_file /var/log/fluentd-journald-docker.pos
  read_from_head true
  tag docker
</source>

<source>
  @type systemd
  filters [{ "_SYSTEMD_UNIT": "kubelet.service" }]
  pos_file /var/log/fluentd-journald-kubelet.pos
  read_from_head true
  tag kubelet
</source>

<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/es-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S.%N
  tag kubernetes.*
  format json
  read_from_head true
  keep_time_key true
</source>

<filter kubernetes.**>
  @type kubernetes_metadata
  preserve_json_log ${KUBERNETES_PRESERVE_JSON_LOG}
EOF

if [ "$KUBERNETES_FETCH_METADATA" != "true" ]; then
cat << EOF >> /etc/fluent/fluent.conf
  kubernetes_url ${KUBERNETES_URL}
  verify_ssl ${KUBERNETES_VERIFY_SSL}
EOF
fi

cat << EOF >> /etc/fluent/fluent.conf
</filter>

<filter kubernetes.**>
  @type record_transformer
  <record>
    $([ -n "${CLUSTER_NAME}" ] && echo cluster_name "${CLUSTER_NAME}")
    $([ -n "${MY_NODE_NAME}" ] && echo node_name "${MY_NODE_NAME}")
  </record>
</filter>

<filter **>
  @type prometheus

  <metric>
    name fluentd_records_total
    type counter
    desc The total number of records read by fluentd.
  </metric>
</filter>

<match **>
  @type elasticsearch$([ "${ELASTICSEARCH_DYNAMIC}" == "true" ] && echo _dynamic)
  @log_level info
  include_tag_key true
  time_key time
  request_timeout ${ELASTICSEARCH_REQUEST_TIMEOUT}
  host ${ELASTICSEARCH_HOST}
  port ${ELASTICSEARCH_PORT}
  scheme ${ELASTICSEARCH_SCHEME}
  $([ -n "${ELASTICSEARCH_USER}" ] && echo user "${ELASTICSEARCH_USER}")
  $([ -n "${ELASTICSEARCH_PASSWORD}" ] && echo password "${ELASTICSEARCH_PASSWORD}")
  logstash_format ${FLUENTD_LOGSTASH_FORMAT}
  logstash_prefix ${FLUENTD_LOGSTASH_PREFIX}
  logstash_dateformat ${FLUENTD_LOGSTASH_DATEFORMAT}

  reload_connections $([ "${ELASTICSEARCH_RELOAD_CONNECTIONS}" == "true" ] && echo true || echo false)
EOF

# Only disable buffering when it's explicitly set to false"
if [ "$FLUENTD_ENABLE_BUFFERING" != "false" ]; then
cat << EOF >> /etc/fluent/fluent.conf
  buffer_type ${FLUENTD_BUFFER_TYPE}
  $([ "${FLUENTD_BUFFER_TYPE}" == "file" ] && echo buffer_path "${FLUENTD_BUFFER_PATH}")
  buffer_queue_full_action ${FLUENTD_BUFFER_QUEUE_FULL_ACTION}
  buffer_chunk_limit ${FLUENTD_BUFFER_CHUNK_LIMIT}
  buffer_queue_limit ${FLUENTD_BUFFER_QUEUE_LIMIT}
  flush_interval ${FLUENTD_FLUSH_INTERVAL}
  retry_limit ${FLUENTD_RETRY_LIMIT}
  $([ "${FLUENTD_DISABLE_RETRY_LIMIT}" == "true" ] && echo disable_retry_limit)
  retry_wait ${FLUENTD_RETRY_WAIT}
  max_retry_wait ${FLUENTD_MAX_RETRY_WAIT}
  num_threads ${FLUENTD_FLUSH_THREADS}
EOF
fi

cat << EOF >> /etc/fluent/fluent.conf
</match>
EOF

fi

exec je fluentd
